const config = {
  clearLocalStorageInNewVersion: true,
  language: 'zh',
  defaultServerLanguage: 'zs',
  recommendedEventRoundTime: 10000,
  balancePollingTime: 15000,
  newsPollingTime: 15000,
  oddsFormat: [
    { label: 'decimal', value: 'decimal' },
    // { label: 'fractional', value: 'fractional' },
    // { label: 'hongkong', value: 'hongkong' },
    // { label: 'malay', value: 'malay' },
  ],
  defaultOddsFormat: 'decimal',
  betTypes: [
    { label: 'single', value: 'single' },
    { label: 'multiple', value: 'multiple' },
    { label: 'system', value: 'system' },
  ],
  defaultBetType: 'single',
  sportIds: [74, 75, 76, 77, 78, 80, 82, 83, 157, 158, 164, 169, 176, 185],
  sportIdMap: {
    '74': { alias: 'callofduty', name: '使命召唤' },
    '75': { alias: 'csgo', name: '反恐精英' },
    '76': { alias: 'dota2', name: '刀塔2' },
    '77': { alias: 'lol', name: '英雄联盟' },
    '78': { alias: 'hearthstone', name: '炉石传说' },
    '80': { alias: 'overwatch', name: '守望先锋' },
    '82': { alias: 'starcraft', name: '星际争霸' },
    '83': { alias: 'starcraft2', name: '星际2' },
    '157': { alias: 'rocketleague', name: '火箭联盟' },
    '158': { alias: 'kingofglory', name: '王者荣耀' },
    '164': { alias: 'pubg', name: '绝地求生' },
    '169': { alias: 'warcraft3', name: '魔兽3' },
    '176': { alias: 'fortnite', name: '堡垒之夜' },
    '185': { alias: 'rainbow6', name: '彩虹六号' },
  },
  nonVersusMarketType: [
    'DoubleChance',
    'CorrectScore',
    'MatchResult',
    'GameLargestMultiKill',
    'P1XP2',
    'Game1LargestMultiKill',
    'Game2LargestMultiKill',
    'Game3LargestMultiKill',
    'Game4LargestMultiKill',
    'Game5LargestMultiKill',
    'Game1FirstDragonType',
    'Game2FirstDragonType',
    'Game3FirstDragonType',
    'Game4FirstDragonType',
    'Game5FirstDragonType',
    'GameFirstActiveRuneType',
  ],
  summaryListData: {
    paths: ['', 'champion', 'result'],
    tabs: {
      upcoming: { name: 'Upcoming', path: '' },
      champion: { name: 'Champion', path: 'champion' },
      result: { name: 'Result', path: 'result' },
    },
  },
  balanceHistoryModal: {
    tabs: {
      balanceHistory: { name: 'balanceHistory' },
    },
  },
  betHistroyModal: {
    tabs: {
      all: { name: 'all' },
      single: { name: 'single' },
      multiple: { name: 'multiple' },
      system: { name: 'system' },
    },
  },
  betTypeCodeConvert: {
    single: 1,
    multiple: 2,
    system: 3,
  },
  defaultDateRange: 7,
  betHistoryDefaultDateRange: 7,
  balanceHistoryDefaultDateRange: 7,
  stakeDecimalPlaceDisplay: 2,
  priceDecimalPlaceDisplay: 2,
  balanceDecimalPlaceDisplay: 3,
  APIBetTypeMap: {
    Single: 'single',
    Multiple: 'multiple',
    System: 'system',
  },
  defaultPriceChangeHandleType: 'ask',
  betslipPriceChangeRadioGroup: [
    { id: 'ask', label: 'Always ask' },
    { id: 'upper', label: 'Accept Higher odds' },
    { id: 'free', label: 'Accept Any odds' },
  ],
  betslipBetCountMAX: 16,
  eventResultOfGameCancel: 3,
  eventResultOfMarketCancel: 4,
  eventResultOfWin: 1,
  eventResultOfNoResult: 0,
  championGamelistTitleTransitionTime: 5000,
  serverReconnectingIntervalTime: 10000,
  serverCode: {
    OK: 0,
    LoginFailed: 1002,
    ProductionNotOpen: 1004,
    ProductionMaintain: 1005,
    InsufficientBalance: 2002,
    SelectionNotExists: 2004,
  },
  langMap: {
    en: 'en',
    id: 'en',
    ko: 'en',
    ms: 'en',
    th: 'en',
    vi: 'en',
    zs: 'zh',
    ja: 'ja',
  },
  teamIconCdnUrl: 'https://cdn.rixinmould.com/images/b/',
};

module.exports = config;
